# Generated by Django 4.2.5 on 2023-09-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0002_rename_machine_usine_machines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usine",
            name="machines",
        ),
        migrations.RemoveField(
            model_name="usine",
            name="recettes",
        ),
        migrations.RemoveField(
            model_name="usine",
            name="stocks",
        ),
        migrations.AddField(
            model_name="usine",
            name="machines",
            field=models.ManyToManyField(to="high_level.machine"),
        ),
        migrations.AddField(
            model_name="usine",
            name="recettes",
            field=models.ManyToManyField(to="high_level.recette"),
        ),
        migrations.AddField(
            model_name="usine",
            name="stocks",
            field=models.ManyToManyField(to="high_level.quantiteingredient"),
        ),
    ]
